# Specify new tasks for roles.

#- id: puppet-agent-plugin_role
#  type: group
#  role: 
#    - primary-controller
#    - controller
#    - cinder
#    - ceph-osd
#    - ironic
#    - mongo
#    - compute
#  parameters:
#    strategy:
#      type: parallel

- id: puppet-agent-plugin-deployment-puppet
  type: puppet
  role: 
    - primary-controller 
    - controller 
    - cinder 
    - ceph-osd 
    - ironic 
    - mongo
    - compute
  version: 2.0.0
  cross-depends:
    - name: deploy_start
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/deploy-puppet-agent.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

#- id: puppet-agent-plugin-post-deployment-sh
#  type: shell
#  role: [puppet-agent-plugin_role]
#  version: 2.0.0
#  cross-depends:
#    - name: post_deployment_start
#  cross-depended-by:
#    - name: post_deployment_end
# #  requires: [post_deployment_start]
# #  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: puppet-agent-plugin-pre-deployment-sh
#  type: shell
#  role: [puppet-agent-plugin_role]
#  version: 2.0.0
#  cross-depends:
#    - name: pre_deployment_start
#  cross-depended-by:
#    - name: pre_deployment_end
# #  requires: [pre_deployment_start]
# #  required_for: [pre_deployment_end]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
