# Specify new tasks for roles.

- id: puppet-agent-plugin-deployment-puppet
  type: puppet
  role: ['/.*/']
  version: 2.0.0
  requires: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/deploy-puppet-agent.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: override-resources
  type: puppet
  role: ['/.*/']
  version: 2.0.0
  requires: [post_deployment_end]
  condition:
    yaql_exp: "$.get('puppet-agent',{}).get('enable-lcm-9_2', false) = true"
  parameters:
    puppet_manifest: "puppet/manifests/override_resources.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600