attributes:
  metadata:
    group: 'other'
  enable-puppet-agent:
    value: true
    label: 'Enable puppet-agent'
    description: 'Disable puppet-agent if you need'
    weight: 25
    type: "checkbox"
  puppet-master-hostname:
    value: 'puppet-master'
    label: 'Hostname of puppet-master'
    description: 'Write hostname of yours puppet-master. For example puppet-master'
    weight: 25
    type: "text"
    regex:
      source: '.+'
      error: "This field should not be empty. Please fill out this field."
  no-dns:
    value: false
    label: 'Use /etc/hosts'
    description: 'If you have not got dns server, set this parametr'
    weight: 25
    type: "checkbox"
  puppet-master-ip:
    value: '10.109.10.10'
    label: 'Ip of puppet-master'
    description: 'Ip address of puppet-master node'
    weight: 25
    type: "text"
    regex:
      source: '.+'
      error: "This field should not be empty. Please fill out this field."
    restrictions:
      - condition: 'settings:puppet-agent.no-dns.value == true'
        action: "hide"
  agent-type:
    value: "cron"
    values:
      - data: "service"
        label: "Puppet agent service"
        description: "Choose this type of puppet-agent if you want use puppet agent as service"
      - data: "cron"
        label: "Puppet agent use cron job"
        description: "Choose this type of puppet-agent if you want use puppet agent from cron"
    label: 'Type puppet agent run'
    weight: 25
    type: "radio"
  cron-conf:
    value: '*/30 * * * * *'
    label: 'Cron configuration'
    description: 'Set up your configuration of cron'
    weight: 25
    type: "text"
    restrictions:
      - condition: 'settings:puppet-agent.agent-type.value == service'
        action: "hide"